In [1]:
import numpy as np

In [22]:
#to create an array with zeros' pass arguments->size of array
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#create an array of ones
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#identity matrix
a=np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#fill a 3x3 matrix with value 9
a=np.full((3,3),9)
a

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [24]:
#problem create a 5X5 matrix in which boundary elements are 1 and inner elements are 0 and the center element is 9
a=np.ones((5,5))
print(a)
b=np.zeros((3,3))
print(b)
#put center element of 3X3 matrix as 9
b[1,1]=9
print(b)
#from column and row 1 to 4(exincluded) replace the elements of a with b
a[1:4,1:4]=b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [31]:
#generates a matrix with random number from 0 to 1
a=np.random.rand(3,3)
a

array([[0.26042533, 0.50876621, 0.83458035],
       [0.01994225, 0.70012584, 0.02631533],
       [0.01671938, 0.1905541 , 0.64874362]])

In [38]:
#generate random numbers integer
#first argument is the max value
a=np.random.randint(20,size=(3,3))
a

array([[10,  9,  7],
       [ 5,  1,  4],
       [ 4, 19,  1]])

In [41]:
#be careful while copying array
a=np.array([1,2,3])
print(a)
b=a
b[1]=9
print(b)
print(a)
#see a is also modified when b was changed
#this happens because b isnt a copy of a , b uses the same object as a 

[1 2 3]
[1 9 3]
[1 9 3]


In [43]:
#to prevent the above case
a=np.array([1,2,3])
print(a)
b=a.copy()
b[1]=9
print(b)
print(a)
#now a copy of a is formed

[1 2 3]
[1 9 3]
[1 2 3]
