In [1]:
import numpy as np

In [3]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
#to find min value in matrix
print(a.min()) #find min value in matrix
print(a.min(axis=0)) #finds min value in each column
print(a.min(axis=1)) #finds min value in each row

1
[1 2 3]
[1 4]


In [7]:
#to find max value in matrix
print(a.max()) #find min value in matrix
print(a.max(axis=0)) #finds min value in each column
print(a.max(axis=1)) #finds min value in each row

6
[4 5 6]
[3 6]


##### DO BASIC MATHS

In [8]:
a+2

array([[3, 4, 5],
       [6, 7, 8]])

In [10]:
a-2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [11]:
a/2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [12]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [22]:
a ** 2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.sin(a)

array([[0.84147098, 0.        , 0.        ],
       [0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.84147098]])

In [19]:
a=np.ones((3,3))
b=np.full((3,3),2)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [17]:
#matrix multiplication
np.matmul(a,b)

array([[6., 6., 6.],
       [6., 6., 6.],
       [6., 6., 6.]])

In [20]:
#find deteminant of a matrix
a=np.identity(3)
np.linalg.det(a)

1.0

In [21]:
#Find eculidean distance
#sqrt((x2-x1)^2+(y2-y1)^2)
#dx=x2-x1
dx=3
dy=4
np.sqrt(np.power(dx,2)+np.power(dy,2))

5.0

In [34]:
a=np.array([[1,2,3],[4,5,6]])
print(np.sum(a))
print(np.sum(a,axis=0)) #sum of elements in array/matrix

21
[5 7 9]
