Problems from https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [1]:
import numpy as np

In [3]:
#Create a 1D array of numbers from 0 to 9
np.array([0,1,2,3,4,5,6,7,8,9])
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Create a 3×3 numpy array of all True’s
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
#Extract all odd numbers from arr
a=np.arange(10)
a[a%2==1]

array([1, 3, 5, 7, 9])

In [10]:
#Replace all odd numbers in arr with -1
a=np.arange(10)
a[a%2==1]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [11]:
#Replace all odd numbers in arr with -1 without changing arr
a=np.arange(10)
b=a.copy()
b[a%2==1]=-1
b

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
#Convert a 1D array to a 2D array with 2 rows
a=np.arange(10)
a.shape
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
#Stack arrays a and b vertically
a=np.ones((3,))
b=np.zeros((3,))
np.vstack((a,b))

array([[1., 1., 1.],
       [0., 0., 0.]])

In [17]:
#Stack the arrays a and b horizontally.
a=np.ones((3,))
b=np.zeros((3,))
np.hstack((a,b))

array([1., 1., 1., 0., 0., 0.])

In [21]:
#Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
#a = np.array([1,2,3])
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [29]:
#Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [30]:
#From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [31]:
#Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [48]:
#Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[((a>5) & (a<=10))]

array([ 6,  9, 10])

In [49]:
#Convert the function maxx that works on two scalars, to work on two arrays.
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])