In [1]:
import numpy as np

In [4]:
a=np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [5]:
np.reshape(a,(3,2)) #to reshape a matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
#vertical stacking
a=np.ones((3,3))
b=np.zeros((3,3))
print(np.vstack((a,b)))
print("\n")
print(np.vstack((a,b,a,b,a)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#horizontal stacking
a=np.ones((3,3))
b=np.zeros((3,3))
print(np.hstack((a,b)))
print(np.hstack((a,b,b,a)))

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]
[[1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1.]]
