In [1]:
import numpy as np

In [5]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [7]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
a[1,2]

8

In [11]:
a[0,:]

array([1, 2, 3, 4, 5])

In [12]:
a[:,1]

array([2, 7])

In [22]:
#a[row index, start index:end index:steps]
#steps means index added i.e. i=i+step in for loop, similar working
a[1,0:4:2]

array([6, 8])

In [18]:
a[1,0:5:2]

array([ 6,  8, 10])

In [23]:
a[1,1:5:3]

array([ 7, 10])

In [46]:
a[1,2]

8

In [48]:
a[1,2]=3 #replaces value

In [49]:
a[1,2]

3

In [51]:
a[1,2]=8

3D array

In [32]:
b=np.array([[[1,2,3],[7,8,9],[4,5,6]]])

In [33]:
b.shape

(1, 3, 3)

In [34]:
b

array([[[1, 2, 3],
        [7, 8, 9],
        [4, 5, 6]]])

In [38]:
b[0,2,1] #b[z_dimension,row,column]

5

In [40]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[15,16,17]]])

In [41]:
c.shape

(2, 3, 3)

In [42]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [15, 16, 17]]])

In [43]:
c[1,1,2]

15